version: "3.4"

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "sawami"
      POSTGRES_PASSWORD: "sawami"
      POSTGRES_DB: "sawami"

  backendservice:
    image: ahmedmq/backend-service:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/sawami"
      SPRING_DATASOURCE_USERNAME: "sawami"
      SPRING_DATASOURCE_PASSWORD: "sawami"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    depends_on:
      - postgres
